### ISSUE TITLE
Docker Build Fails

### ISSUE THREAD

**Issue by tunix** [OrchidTechnologies/orchid#100]
**Describe the bug**

Docker builds fail upfront without even starting to build with the following error:

```
$ ./env/docker.sh
Unable to find image 'ubuntu:bionic' locally
bionic: Pulling from library/ubuntu
25fa05cd42bd: Pull complete
Digest: sha256:139b3846cee2e63de9ced83cee7023a2d95763ee2573e5b0ab6dea9dfbd4db8f
Status: Downloaded newer image for ubuntu:bionic
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mnt/env/setup-dkr.sh": stat /mnt/env/setup-dkr.sh: no such file or directory: unknown.
```

**To Reproduce**
1. Clone repository
2. Go to the root of the repository
3. Issue the following command: `./env/docker.sh`

**Expected behavior**

No error should be thrown and build should start.

**Device information:**
 - Device: System76 Lemur Pro
 - OS: Pop!_OS 21.04
 - Application Version: Git Master

**Additional context**

I'm trying to build the Linux client to connect to the VPN.

**Comment by saurik** [comment]
@tunix Would you mind telling me the value of $PWD?

**Comment by saurik** [comment]
Oh, actually, maybe this isn't really easy: if you want to build the Linux client you need to be in cli-shared. If you are just sitting in the top-level directory--which you might be, despite the note in the README--that isn't going to support the Docker build stuff, as that is an all-configurations build for distribution (and is only supported on macOS natively, due to iOS and macOS targets).

**Comment by saurik** [comment]
Ah ha: and you even said "go to the root of the repository"... just go to the project folder for the client first.
