### ISSUE TITLE
Orchid's current trust requirements are a non-starter for the conscientious

### ISSUE THREAD

**Issue by softwarecreations** [OrchidTechnologies/orchid#111]
**Firstly, I want to say, I love what you're doing and love the concept.**

As Orchid exists right now, there is a large barrier, or a lot of friction to entry that I need to personally overcome to consider trying it out. And if I feel that way, then guaranteed there are a lot more potential users who feel the same. I'm not exactly 007 but I do practice some basic digital hygiene, which is totally lacking here.

I understand that dev resources are constrained and whatever, but solving these problems is not hard and it's critical for Orchid to be taken seriously at all by many potential users.

--

**The problems**

Currently if a Linux user wants to try out Orchid, they have to go here and run some binary blobs from Microsoft with blind faith
https://github.com/OrchidTechnologies/orchid/releases

If I had such blind faith in Microsoft, maybe I'd be using Windows.

If users want to build from source, the readme doesn't have any build instructions.
The only alternative, is Docker, which as you recognize, is super cringey.

On Android, Orchid isn't on F-Droid. So it's a non-starter on Android as well. Especially since there's no way verifiable blob to sideload; as above.

--

**Two easy solutions**

Firstly build instructions won't be that hard to make. Perhaps I can contirbute?

Secondly your blobs SHA512 sums should be signed with your PGP key, which is hosted somewhere that inspires some level of trust or assurance of authenticity. Perhaps you could store your PGP in Ethereum, sign it with the same dev key that you publish the smart contract with.

--

**Conclusion**

Without either of these, the project is a complete non-starter for the conscientious at this time.

What is the point of a security product, that if used, weakens security? To become more secure, I must install blobs from Microsoft? Really?

--

**No hard feelings**

Peace, love, freedom, autonomy and all that good stuff.

**Comment by saurik** [comment]
> If users want to build from source, the readme doesn't have any build instructions.

Go into the folder you want to compile and type "make".

**Comment by saurik** [comment]
(Oh: and as also noted in the readme, you need to have Rust, clang with lld, Python3, and meson installed. But this is all documented in the build instructions in the readme, and would also be obvious when the build prints something like "cargo: command not found". Honestly, if you haven't managed to compile Orchid, it is more likely because you didn't try, not because it is either difficult or undocumented. If you get some actual error that seems specific to your system, I will absolutely treat that as a bug and fix it ASAP.)

**Comment by saurik** [comment]
> ...sign it with the same dev key that you publish the smart contract with.

So, our project's smart contracts (not including the OXT token, which in some sense isn't actually related to this software...) are intended to be singletons, as the entire premise is that you should trust the code to be correct and not the person deploying the contract. (With a singleton, the address of the contract is fixed by a hash of its code, and can be deployed by anyone.) There thereby is no key which you can *or should* trust involved. The directory contract is sadly *not* a singleton (as I didn't understand this property of Ethereum at the time), but you would still decide to trust it by recompiling it yourself and verifying the codehash... I deployed it--on purpose--using an extremely insecure key "owned by" SaurikIT (one that would not at all be reasonable to sign anything secure with), as the security properties of the system are unrelated to who deployed it. Like, if I gave you the private key--or lost it, etc.--it would not affect the security of the contracts.

FWIW, if it is useful to understand this, I care a lot about and am quite experienced with reproducible builds (I have been doing deterministic build systems since before Debian, which is awkwardly famous for their efforts in that space, as part of the toolchain and userland for jailbroken iPhones back in late 2007 and early 2008) and not only should Orchid's server and "cli" builds be fully reproducible, the GitHub CI setup--which is code in the repository you can just follow along with to reproduce the build (so there is no sleight of hand)--even builds the Linux server daemon twice on entirely different systems (once on a messy macOS box from Axure and one on Linux inside of clean a docker setup) to verify the result is bit-for-bit identical, as I consider it a build regression if that fails ;P.
