### ISSUE TITLE
genai.orchid.com connect button does not work.

### ISSUE THREAD

**Issue by robtweisz** [OrchidTechnologies/orchid#176]
genai.orchid.com connect button does not work.

Using windows, brave browser, the web version of genai.orchid.com does not properly prompt MetaMask when the connect button is pressed.

**Comment by saurik** [comment]
Huh. I can confirm that the Connect button doesn't do anything for me either. I'm using MetaMask with Firefox on Linux. I've poked some people and will follow up on this when they are awake tomorrow.

**Comment by saurik** [comment]
Ok! So it turns out that that Connect button didn't do what you and I assumed it might, which led to some crossed wires in the communication. The idea is that, once you provide your Orchid credentials using the Account button, this button--sometimes named Connect and sometimes named Reroll--causes the selection of a backend provider.

In fact, the GenAI dapp doesn't really use Metamask at all, as our probabilistic streaming nanopayments system is effectively a slightly-awkward "L2" network that might should need its own separate wallet software (or if this could be done maybe a plugin for Metamask? I think I heard they support those now?) for better securing access to its keys and allocating budgets to specific applications.

As it stands, however, the wallet functionality of Orchid probabilistic streaming nanopayment accounts is just embedded ad hoc into various applications that use it, including both our VPN clients and this demo we threw together that provides access to generative AI models. I could see renaming the the Account button to Connect, but for now we have at least renamed the Connect button to Reroll, so you don't think to click it first.

**Comment by robtweisz** [comment]
Woops. Thank you.
