### ISSUE TITLE
App is not installing

### ISSUE THREAD

**Issue by bharathbenne** [OrchidTechnologies/orchid#70]
![Screenshot_20210203-225826](https://user-images.githubusercontent.com/73907668/106785543-7f6c2c80-6673-11eb-8ee6-5a4ae5288e30.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information:**
 - Application Version [e.g. 22]

**Additional context**

**Comment by CryptoSal2020** [comment]
Hello,

Thanks for reporting your issue.

You are required to fill out the template if you wish to receive some sort of assistance.

Anyway, this doesn't seem to be a problem with the app - it's an Android issue.

Have you tried to install the app from the Play Store or using the APK file available here on GitHub?

Try to follow the steps below:

If you see Orchid in your available apps from the device settings:

Force stop 
Clear cache
Clear data
Uninstall

Then reset your app permissions to default (you're not going to use any personal data by doing that) and shut down your phone (not necessary but always a good thing to do).

If you're tech savvy, try to start up your Android device into recovery mode and wipe the cache, then reboot.

Try to install the app from the Play Store (if your Play Store country location is set to France or China, you'll need to use the APK file).

Let us know if the above suggestions work for you. If not, you need to give us some more information, such as device version, model, make, etc...

Oh, ensure you have enough storage left...

Cheers,
Salvatore

**Comment by saurik** [comment]
FWIW, no one is "required" to fill out the template to receive assistance: that template was added by someone who previously worked at Orchid doing developer relations, and I think it is always valid to just type whatever you want instead; that said... you definitely need to provide enough context for us to be able to help ;P. (I feel a need to be clear here that CryptoSal2020 is not affiliated with the Orchid project.) That said, there isn't really enough information here to keep this open.

I went ahead just now and verified that I could download the latest "release" APK from Orchid to install using the browser on Android, and that worked fine, so there at least isn't some "obvious" issue here... one thing to note: if you are trying to download an _artifact_ instead of a release, those are signed with a random key (as they are just part of an insecure CI pipeline), and so you can't install those over any existing install of Orchid (including a previous CI build, I believe).

As this is being filed on the GitHub project, my next thought is maybe you downloaded the code and built the Android app and are now trying to install it yourself? Doing that will generate a random key (as clearly we aren't going to distribute our private app distribution key ;P), and so you won't be able to install it on top of an existing install from the App Store. It should continue to use the same key for subsequent builds, so you can upgrade your own builds.

Otherwise, I'm not sure if any of the other suggestions so far are helpful--in particular, this is in fact much more likely to be an issue with the download than an "Android issue"--so, to the extent to which this is still a problem, you should explain specifically how you downloaded the file you are you installing (not merely where from) and re-open this issue. (The next step, if there's nothing obvious there, will be to get you to look at the Android debug logs during the install.)

THAT ALL SAID: I get the feeling like this is more of an end-user support problem than a developer issue. We actually have a customer support process, which is going to make a very different set of assumptions and--for an end user--is going to be a more appropriate (and, dare I say, "useful") way to get help. To get a hold of them, send an e-mail to contact@orchid.com (which will put you in some kind of issue tracker attached to Orchid sales, marketing, and customer support).
