### ISSUE TITLE
Create a fast way to recover an Orchid account due to lost signer key

### ISSUE THREAD

**Issue by zjmo** [OrchidTechnologies/orchid#80]
I'm trying to recover the funds on an Orchid account after I've realized that I've copied the wrong signer key. I could not find any documentation on how it should be done. The unresponsive GUI is not helping. I would add little FAQ on this matter.

**Comment by dereksilva** [comment]
Unfortunately if you have completely lost record of the signer key, there's nothing we can do to help you. That's like losing the secret key or passphrase to your wallet.

**Comment by zjmo** [comment]
Well, actually I still had the funder key so I recovered the deposit by interacting directly with the contract. They GUI is just unresposive and does not represent what is happening on the background with the contract.

**Comment by saurik** [comment]
@zjmo FWIW, I had correctly understood and agreed with your issue, and so had put this--along with all the other issues that had you had filed--in the queue of tasks that our project manager is coordinating with for the cycle of changes they are about to make to the dapp.

**Comment by zjmo** [comment]
@saurik Thanks. I've just tried to give an advice as user. The GUI is still important especially if metamask result in a strange fee estimation. Might it be related to the function 'look' in the contract? I've still not be able to read from it. Anyway chances are that I'm doing something wrong.

**Comment by danopato** [comment]
This issue is addressed in the new account management dapp. Given a known signer address and an attached funder wallet the process for withdrawing your funds is pretty straightforward (we are still cleaning up some terminology and info text to make everything as clear as possible).

Signer key management has been removed from the dapp and is now exclusively done through the client app. This should make it harder to lose track of your signers and also more clear which signer is used when working in the dapp.
