### ISSUE TITLE
List of providers?

### ISSUE THREAD

**Issue by vindberg** [OrchidTechnologies/orchid#91]
Would be possible to see a list of all providers with each of their geo location? Or is it not online yet?

Thanks. Interesting project.

**Comment by saurik** [comment]
So, Orchid providers do not canonically have a "geolocation"; otherwise, you are welcome to look at https://status.orchid.com/, which is running a copy of the Orchid dashboard (code is under tst-network: you should easily be able to run it yourself) and shows a sampled IP address from the provider (right now, the major providers each only have one IP address, so this might be useful, but in a world where providers each had a worldwide fleet of nodes it would no longer be relevant).

**Comment by vindberg** [comment]
Thanks for the response. So I would not be able to define which geo I wanted to use through the network? For instance, streaming from Netflix US while in another country?

**Comment by saurik** [comment]
@vindberg Netflix generally attempts to block VPN services, so a decentralized network proxy isn't going to be able to solve that use case no matter what information is available.

**Comment by vindberg** [comment]
This is very unfortunate then. I believe many people use VPN for exactly this purpose.

**Comment by saurik** [comment]
@vindberg FWIW, even centralized VPN services--which are at an inherent advantage here--struggle to support that use case; the only provider I've heard of that everyone reports as fairly consistently being able win in the cat and mouse game against the large streaming providers is NordVPN (and, as I've mentioned elsewhere, they do it with somewhat complex internal routing and even some "dirty tricks" involving malware installs on random peoples' computers)... if you simply consider the problem for a moment from the side of Netflix, it is hopefully pretty easy to see why it is so easy for them to detect, catalog, and block VPN providers.
